In [23]:
import requests
import pandas as pd
from sqlalchemy import create_engine
import os

def extract_products(sbd_start: int = 34000001, sbd_end: int = 34000210) -> pd.DataFrame:
    sbd_start = 34000001
    sbd_end = 34000210
    df_list = []
    session = requests.Session()

    for sbd in range(sbd_start, sbd_end):
        url = f"https://vietnamnet.vn/giao-duc/diem-thi/tra-cuu-diem-thi-tot-nghiep-thpt/2023/{sbd}.html"
        response = session.get(url)
        if response.ok:
            tables = pd.read_html(url)
            desired_table = tables[0].transpose()
            desired_table.columns = desired_table.iloc[0]
            desired_table = desired_table[1:]
            desired_table['SBD'] = sbd
            df_list.append(desired_table)

    session.close()  # Close the session after use

    if df_list:
        df = pd.concat(df_list, ignore_index=True)
        return df
    else:
        return pd.DataFrame()  # Trả về DataFrame rỗng nếu không có dữ liệu

In [24]:
df = extract_products()
df.head()

Môn Toán    Lí   Hóa Sinh   Văn Ngoại ngữ       SBD    Sử  Địa GDCD
0    8.2  8.25   8.5  8.0   7.5       6.8  34000001   NaN  NaN  NaN
1    3.2   NaN   NaN  NaN   5.0       2.8  34000002   3.0  4.0  3.0
2    7.6  7.25   8.5  5.5  6.75       4.0  34000003   NaN  NaN  NaN
3    7.4   NaN   NaN  NaN  8.25       4.4  34000004  6.75  8.0  9.5
4    8.6   9.0  7.25  7.0   4.5       5.4  34000005   NaN  NaN  NaN

In [25]:
df.head(100)

Môn Toán    Lí   Hóa  Sinh   Văn Ngoại ngữ       SBD    Sử   Địa  GDCD
0    8.2  8.25   8.5   8.0   7.5       6.8  34000001   NaN   NaN   NaN
1    3.2   NaN   NaN   NaN   5.0       2.8  34000002   3.0   4.0   3.0
2    7.6  7.25   8.5   5.5  6.75       4.0  34000003   NaN   NaN   NaN
3    7.4   NaN   NaN   NaN  8.25       4.4  34000004  6.75   8.0   9.5
4    8.6   9.0  7.25   7.0   4.5       5.4  34000005   NaN   NaN   NaN
..   ...   ...   ...   ...   ...       ...       ...   ...   ...   ...
95   8.0  8.25  7.75  4.25  5.25       4.6  34000096   NaN   NaN   NaN
96   7.6  8.75   7.5   5.5   6.5       5.0  34000097   NaN   NaN   NaN
97   7.0   8.0  7.75   5.5  5.25       5.4  34000098   NaN   NaN   NaN
98   5.6   NaN   NaN   NaN   5.5       3.0  34000099   6.0   6.0  8.75
99   7.2   NaN   NaN   NaN  5.25       3.8  34000100   5.5  6.25   8.0

[100 rows x 10 columns]

In [1]:
from cryptography.fernet import Fernet
import base64

key = "VgMozX-JxN-80PGluGBjihVp-rdjJse-POU4DzTK2gg="
try:
    decoded = base64.urlsafe_b64decode(key)
    print("Decoded length:", len(decoded))
    Fernet(key)  # sẽ lỗi nếu key không hợp lệ
    print("Key hợp lệ!")
except Exception as e:
    print("Key KHÔNG hợp lệ:", e)

Decoded length: 32
Key hợp lệ!